package com.kakarote.common.log.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OperateLog.proto

public final class OperateLogEntity {
    private OperateLogEntity() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface EntityOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Entity)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 请求地址
         * </pre>
         *
         * <code>string requestUri = 1;</code>
         *
         * @return The requestUri.
         */
        String getRequestUri();

        /**
         * <pre>
         * 请求地址
         * </pre>
         *
         * <code>string requestUri = 1;</code>
         *
         * @return The bytes for requestUri.
         */
        com.google.protobuf.ByteString
        getRequestUriBytes();

        /**
         * <pre>
         * 操作行为
         * </pre>
         *
         * <code>uint32 behavior = 2;</code>
         *
         * @return The behavior.
         */
        int getBehavior();

        /**
         * <pre>
         * 所属应用
         * </pre>
         *
         * <code>uint32 apply = 3;</code>
         *
         * @return The apply.
         */
        int getApply();

        /**
         * <pre>
         * 客户端IP
         * </pre>
         *
         * <code>string clientIp = 4;</code>
         *
         * @return The clientIp.
         */
        String getClientIp();

        /**
         * <pre>
         * 客户端IP
         * </pre>
         *
         * <code>string clientIp = 4;</code>
         *
         * @return The bytes for clientIp.
         */
        com.google.protobuf.ByteString
        getClientIpBytes();

        /**
         * <pre>
         * 操作模块
         * </pre>
         *
         * <code>uint32 module = 5;</code>
         *
         * @return The module.
         */
        int getModule();

        /**
         * <pre>
         * 创建人
         * </pre>
         *
         * <code>uint64 createUserId = 6;</code>
         *
         * @return The createUserId.
         */
        long getCreateUserId();

        /**
         * <pre>
         * 公司ID
         * </pre>
         *
         * <code>uint64 companyId = 7;</code>
         *
         * @return The companyId.
         */
        long getCompanyId();

        /**
         * <pre>
         * 创建时间
         * </pre>
         *
         * <code>string createTime = 8;</code>
         *
         * @return The createTime.
         */
        String getCreateTime();

        /**
         * <pre>
         * 创建时间
         * </pre>
         *
         * <code>string createTime = 8;</code>
         *
         * @return The bytes for createTime.
         */
        com.google.protobuf.ByteString
        getCreateTimeBytes();

        /**
         * <pre>
         * 操作对象
         * </pre>
         *
         * <code>string operation_obj = 9;</code>
         *
         * @return The operationObj.
         */
        String getOperationObj();

        /**
         * <pre>
         * 操作对象
         * </pre>
         *
         * <code>string operation_obj = 9;</code>
         *
         * @return The bytes for operationObj.
         */
        com.google.protobuf.ByteString
        getOperationObjBytes();

        /**
         * <pre>
         * 操作详情
         * </pre>
         *
         * <code>string operation_info = 10;</code>
         *
         * @return The operationInfo.
         */
        String getOperationInfo();

        /**
         * <pre>
         * 操作详情
         * </pre>
         *
         * <code>string operation_info = 10;</code>
         *
         * @return The bytes for operationInfo.
         */
        com.google.protobuf.ByteString
        getOperationInfoBytes();

        /**
         * <pre>
         * 访问类型
         * </pre>
         *
         * <code>string equipmentType = 11;</code>
         *
         * @return The equipmentType.
         */
        String getEquipmentType();

        /**
         * <pre>
         * 访问类型
         * </pre>
         *
         * <code>string equipmentType = 11;</code>
         *
         * @return The bytes for equipmentType.
         */
        com.google.protobuf.ByteString
        getEquipmentTypeBytes();

        /**
         * <pre>
         * 操作类型
         * </pre>
         *
         * <code>uint32 type = 12;</code>
         *
         * @return The type.
         */
        int getType();
    }

    /**
     * Protobuf type {@code Entity}
     */
    public static final class Entity extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Entity)
            EntityOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Entity.newBuilder() to construct.
        private Entity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Entity() {
            requestUri_ = "";
            clientIp_ = "";
            createTime_ = "";
            operationObj_ = "";
            operationInfo_ = "";
            equipmentType_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new Entity();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Entity(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            requestUri_ = s;
                            break;
                        }
                        case 16: {

                            behavior_ = input.readUInt32();
                            break;
                        }
                        case 24: {

                            apply_ = input.readUInt32();
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            clientIp_ = s;
                            break;
                        }
                        case 40: {

                            module_ = input.readUInt32();
                            break;
                        }
                        case 48: {

                            createUserId_ = input.readUInt64();
                            break;
                        }
                        case 56: {

                            companyId_ = input.readUInt64();
                            break;
                        }
                        case 66: {
                            String s = input.readStringRequireUtf8();

                            createTime_ = s;
                            break;
                        }
                        case 74: {
                            String s = input.readStringRequireUtf8();

                            operationObj_ = s;
                            break;
                        }
                        case 82: {
                            String s = input.readStringRequireUtf8();

                            operationInfo_ = s;
                            break;
                        }
                        case 90: {
                            String s = input.readStringRequireUtf8();

                            equipmentType_ = s;
                            break;
                        }
                        case 96: {

                            type_ = input.readUInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return OperateLogEntity.internal_static_Entity_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return OperateLogEntity.internal_static_Entity_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Entity.class, Builder.class);
        }

        public static final int REQUESTURI_FIELD_NUMBER = 1;
        private volatile Object requestUri_;

        /**
         * <pre>
         * 请求地址
         * </pre>
         *
         * <code>string requestUri = 1;</code>
         *
         * @return The requestUri.
         */
        @Override
        public String getRequestUri() {
            Object ref = requestUri_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                requestUri_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 请求地址
         * </pre>
         *
         * <code>string requestUri = 1;</code>
         *
         * @return The bytes for requestUri.
         */
        @Override
        public com.google.protobuf.ByteString
        getRequestUriBytes() {
            Object ref = requestUri_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                requestUri_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BEHAVIOR_FIELD_NUMBER = 2;
        private int behavior_;

        /**
         * <pre>
         * 操作行为
         * </pre>
         *
         * <code>uint32 behavior = 2;</code>
         *
         * @return The behavior.
         */
        @Override
        public int getBehavior() {
            return behavior_;
        }

        public static final int APPLY_FIELD_NUMBER = 3;
        private int apply_;

        /**
         * <pre>
         * 所属应用
         * </pre>
         *
         * <code>uint32 apply = 3;</code>
         *
         * @return The apply.
         */
        @Override
        public int getApply() {
            return apply_;
        }

        public static final int CLIENTIP_FIELD_NUMBER = 4;
        private volatile Object clientIp_;

        /**
         * <pre>
         * 客户端IP
         * </pre>
         *
         * <code>string clientIp = 4;</code>
         *
         * @return The clientIp.
         */
        @Override
        public String getClientIp() {
            Object ref = clientIp_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                clientIp_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 客户端IP
         * </pre>
         *
         * <code>string clientIp = 4;</code>
         *
         * @return The bytes for clientIp.
         */
        @Override
        public com.google.protobuf.ByteString
        getClientIpBytes() {
            Object ref = clientIp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                clientIp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MODULE_FIELD_NUMBER = 5;
        private int module_;

        /**
         * <pre>
         * 操作模块
         * </pre>
         *
         * <code>uint32 module = 5;</code>
         *
         * @return The module.
         */
        @Override
        public int getModule() {
            return module_;
        }

        public static final int CREATEUSERID_FIELD_NUMBER = 6;
        private long createUserId_;

        /**
         * <pre>
         * 创建人
         * </pre>
         *
         * <code>uint64 createUserId = 6;</code>
         *
         * @return The createUserId.
         */
        @Override
        public long getCreateUserId() {
            return createUserId_;
        }

        public static final int COMPANYID_FIELD_NUMBER = 7;
        private long companyId_;

        /**
         * <pre>
         * 公司ID
         * </pre>
         *
         * <code>uint64 companyId = 7;</code>
         *
         * @return The companyId.
         */
        @Override
        public long getCompanyId() {
            return companyId_;
        }

        public static final int CREATETIME_FIELD_NUMBER = 8;
        private volatile Object createTime_;

        /**
         * <pre>
         * 创建时间
         * </pre>
         *
         * <code>string createTime = 8;</code>
         *
         * @return The createTime.
         */
        @Override
        public String getCreateTime() {
            Object ref = createTime_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                createTime_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 创建时间
         * </pre>
         *
         * <code>string createTime = 8;</code>
         *
         * @return The bytes for createTime.
         */
        @Override
        public com.google.protobuf.ByteString
        getCreateTimeBytes() {
            Object ref = createTime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                createTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int OPERATION_OBJ_FIELD_NUMBER = 9;
        private volatile Object operationObj_;

        /**
         * <pre>
         * 操作对象
         * </pre>
         *
         * <code>string operation_obj = 9;</code>
         *
         * @return The operationObj.
         */
        @Override
        public String getOperationObj() {
            Object ref = operationObj_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                operationObj_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 操作对象
         * </pre>
         *
         * <code>string operation_obj = 9;</code>
         *
         * @return The bytes for operationObj.
         */
        @Override
        public com.google.protobuf.ByteString
        getOperationObjBytes() {
            Object ref = operationObj_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                operationObj_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int OPERATION_INFO_FIELD_NUMBER = 10;
        private volatile Object operationInfo_;

        /**
         * <pre>
         * 操作详情
         * </pre>
         *
         * <code>string operation_info = 10;</code>
         *
         * @return The operationInfo.
         */
        @Override
        public String getOperationInfo() {
            Object ref = operationInfo_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                operationInfo_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 操作详情
         * </pre>
         *
         * <code>string operation_info = 10;</code>
         *
         * @return The bytes for operationInfo.
         */
        @Override
        public com.google.protobuf.ByteString
        getOperationInfoBytes() {
            Object ref = operationInfo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                operationInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EQUIPMENTTYPE_FIELD_NUMBER = 11;
        private volatile Object equipmentType_;

        /**
         * <pre>
         * 访问类型
         * </pre>
         *
         * <code>string equipmentType = 11;</code>
         *
         * @return The equipmentType.
         */
        @Override
        public String getEquipmentType() {
            Object ref = equipmentType_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                equipmentType_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 访问类型
         * </pre>
         *
         * <code>string equipmentType = 11;</code>
         *
         * @return The bytes for equipmentType.
         */
        @Override
        public com.google.protobuf.ByteString
        getEquipmentTypeBytes() {
            Object ref = equipmentType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                equipmentType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 12;
        private int type_;

        /**
         * <pre>
         * 操作类型
         * </pre>
         *
         * <code>uint32 type = 12;</code>
         *
         * @return The type.
         */
        @Override
        public int getType() {
            return type_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRequestUriBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestUri_);
            }
            if (behavior_ != 0) {
                output.writeUInt32(2, behavior_);
            }
            if (apply_ != 0) {
                output.writeUInt32(3, apply_);
            }
            if (!getClientIpBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientIp_);
            }
            if (module_ != 0) {
                output.writeUInt32(5, module_);
            }
            if (createUserId_ != 0L) {
                output.writeUInt64(6, createUserId_);
            }
            if (companyId_ != 0L) {
                output.writeUInt64(7, companyId_);
            }
            if (!getCreateTimeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, createTime_);
            }
            if (!getOperationObjBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, operationObj_);
            }
            if (!getOperationInfoBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 10, operationInfo_);
            }
            if (!getEquipmentTypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 11, equipmentType_);
            }
            if (type_ != 0) {
                output.writeUInt32(12, type_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRequestUriBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestUri_);
            }
            if (behavior_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, behavior_);
            }
            if (apply_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, apply_);
            }
            if (!getClientIpBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientIp_);
            }
            if (module_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, module_);
            }
            if (createUserId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, createUserId_);
            }
            if (companyId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(7, companyId_);
            }
            if (!getCreateTimeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, createTime_);
            }
            if (!getOperationObjBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, operationObj_);
            }
            if (!getOperationInfoBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, operationInfo_);
            }
            if (!getEquipmentTypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, equipmentType_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(12, type_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Entity)) {
                return super.equals(obj);
            }
            Entity other = (Entity) obj;

            if (!getRequestUri()
                    .equals(other.getRequestUri())) return false;
            if (getBehavior()
                    != other.getBehavior()) return false;
            if (getApply()
                    != other.getApply()) return false;
            if (!getClientIp()
                    .equals(other.getClientIp())) return false;
            if (getModule()
                    != other.getModule()) return false;
            if (getCreateUserId()
                    != other.getCreateUserId()) return false;
            if (getCompanyId()
                    != other.getCompanyId()) return false;
            if (!getCreateTime()
                    .equals(other.getCreateTime())) return false;
            if (!getOperationObj()
                    .equals(other.getOperationObj())) return false;
            if (!getOperationInfo()
                    .equals(other.getOperationInfo())) return false;
            if (!getEquipmentType()
                    .equals(other.getEquipmentType())) return false;
            if (getType()
                    != other.getType()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REQUESTURI_FIELD_NUMBER;
            hash = (53 * hash) + getRequestUri().hashCode();
            hash = (37 * hash) + BEHAVIOR_FIELD_NUMBER;
            hash = (53 * hash) + getBehavior();
            hash = (37 * hash) + APPLY_FIELD_NUMBER;
            hash = (53 * hash) + getApply();
            hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
            hash = (53 * hash) + getClientIp().hashCode();
            hash = (37 * hash) + MODULE_FIELD_NUMBER;
            hash = (53 * hash) + getModule();
            hash = (37 * hash) + CREATEUSERID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getCreateUserId());
            hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getCompanyId());
            hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
            hash = (53 * hash) + getCreateTime().hashCode();
            hash = (37 * hash) + OPERATION_OBJ_FIELD_NUMBER;
            hash = (53 * hash) + getOperationObj().hashCode();
            hash = (37 * hash) + OPERATION_INFO_FIELD_NUMBER;
            hash = (53 * hash) + getOperationInfo().hashCode();
            hash = (37 * hash) + EQUIPMENTTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getEquipmentType().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Entity parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Entity parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Entity parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Entity parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Entity parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Entity parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Entity parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Entity parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Entity parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Entity parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Entity parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Entity parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Entity prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Entity}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Entity)
                EntityOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return OperateLogEntity.internal_static_Entity_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return OperateLogEntity.internal_static_Entity_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Entity.class, Builder.class);
            }

            // Construct using OperateLogEntity.Entity.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                requestUri_ = "";

                behavior_ = 0;

                apply_ = 0;

                clientIp_ = "";

                module_ = 0;

                createUserId_ = 0L;

                companyId_ = 0L;

                createTime_ = "";

                operationObj_ = "";

                operationInfo_ = "";

                equipmentType_ = "";

                type_ = 0;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return OperateLogEntity.internal_static_Entity_descriptor;
            }

            @Override
            public Entity getDefaultInstanceForType() {
                return Entity.getDefaultInstance();
            }

            @Override
            public Entity build() {
                Entity result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Entity buildPartial() {
                Entity result = new Entity(this);
                result.requestUri_ = requestUri_;
                result.behavior_ = behavior_;
                result.apply_ = apply_;
                result.clientIp_ = clientIp_;
                result.module_ = module_;
                result.createUserId_ = createUserId_;
                result.companyId_ = companyId_;
                result.createTime_ = createTime_;
                result.operationObj_ = operationObj_;
                result.operationInfo_ = operationInfo_;
                result.equipmentType_ = equipmentType_;
                result.type_ = type_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Entity) {
                    return mergeFrom((Entity) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Entity other) {
                if (other == Entity.getDefaultInstance()) return this;
                if (!other.getRequestUri().isEmpty()) {
                    requestUri_ = other.requestUri_;
                    onChanged();
                }
                if (other.getBehavior() != 0) {
                    setBehavior(other.getBehavior());
                }
                if (other.getApply() != 0) {
                    setApply(other.getApply());
                }
                if (!other.getClientIp().isEmpty()) {
                    clientIp_ = other.clientIp_;
                    onChanged();
                }
                if (other.getModule() != 0) {
                    setModule(other.getModule());
                }
                if (other.getCreateUserId() != 0L) {
                    setCreateUserId(other.getCreateUserId());
                }
                if (other.getCompanyId() != 0L) {
                    setCompanyId(other.getCompanyId());
                }
                if (!other.getCreateTime().isEmpty()) {
                    createTime_ = other.createTime_;
                    onChanged();
                }
                if (!other.getOperationObj().isEmpty()) {
                    operationObj_ = other.operationObj_;
                    onChanged();
                }
                if (!other.getOperationInfo().isEmpty()) {
                    operationInfo_ = other.operationInfo_;
                    onChanged();
                }
                if (!other.getEquipmentType().isEmpty()) {
                    equipmentType_ = other.equipmentType_;
                    onChanged();
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Entity parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Entity) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object requestUri_ = "";

            /**
             * <pre>
             * 请求地址
             * </pre>
             *
             * <code>string requestUri = 1;</code>
             *
             * @return The requestUri.
             */
            public String getRequestUri() {
                Object ref = requestUri_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    requestUri_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 请求地址
             * </pre>
             *
             * <code>string requestUri = 1;</code>
             *
             * @return The bytes for requestUri.
             */
            public com.google.protobuf.ByteString
            getRequestUriBytes() {
                Object ref = requestUri_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    requestUri_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 请求地址
             * </pre>
             *
             * <code>string requestUri = 1;</code>
             *
             * @param value The requestUri to set.
             * @return This builder for chaining.
             */
            public Builder setRequestUri(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                requestUri_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求地址
             * </pre>
             *
             * <code>string requestUri = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRequestUri() {

                requestUri_ = getDefaultInstance().getRequestUri();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求地址
             * </pre>
             *
             * <code>string requestUri = 1;</code>
             *
             * @param value The bytes for requestUri to set.
             * @return This builder for chaining.
             */
            public Builder setRequestUriBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                requestUri_ = value;
                onChanged();
                return this;
            }

            private int behavior_;

            /**
             * <pre>
             * 操作行为
             * </pre>
             *
             * <code>uint32 behavior = 2;</code>
             *
             * @return The behavior.
             */
            @Override
            public int getBehavior() {
                return behavior_;
            }

            /**
             * <pre>
             * 操作行为
             * </pre>
             *
             * <code>uint32 behavior = 2;</code>
             *
             * @param value The behavior to set.
             * @return This builder for chaining.
             */
            public Builder setBehavior(int value) {

                behavior_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作行为
             * </pre>
             *
             * <code>uint32 behavior = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBehavior() {

                behavior_ = 0;
                onChanged();
                return this;
            }

            private int apply_;

            /**
             * <pre>
             * 所属应用
             * </pre>
             *
             * <code>uint32 apply = 3;</code>
             *
             * @return The apply.
             */
            @Override
            public int getApply() {
                return apply_;
            }

            /**
             * <pre>
             * 所属应用
             * </pre>
             *
             * <code>uint32 apply = 3;</code>
             *
             * @param value The apply to set.
             * @return This builder for chaining.
             */
            public Builder setApply(int value) {

                apply_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 所属应用
             * </pre>
             *
             * <code>uint32 apply = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearApply() {

                apply_ = 0;
                onChanged();
                return this;
            }

            private Object clientIp_ = "";

            /**
             * <pre>
             * 客户端IP
             * </pre>
             *
             * <code>string clientIp = 4;</code>
             *
             * @return The clientIp.
             */
            public String getClientIp() {
                Object ref = clientIp_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    clientIp_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 客户端IP
             * </pre>
             *
             * <code>string clientIp = 4;</code>
             *
             * @return The bytes for clientIp.
             */
            public com.google.protobuf.ByteString
            getClientIpBytes() {
                Object ref = clientIp_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    clientIp_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 客户端IP
             * </pre>
             *
             * <code>string clientIp = 4;</code>
             *
             * @param value The clientIp to set.
             * @return This builder for chaining.
             */
            public Builder setClientIp(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                clientIp_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 客户端IP
             * </pre>
             *
             * <code>string clientIp = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearClientIp() {

                clientIp_ = getDefaultInstance().getClientIp();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 客户端IP
             * </pre>
             *
             * <code>string clientIp = 4;</code>
             *
             * @param value The bytes for clientIp to set.
             * @return This builder for chaining.
             */
            public Builder setClientIpBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                clientIp_ = value;
                onChanged();
                return this;
            }

            private int module_;

            /**
             * <pre>
             * 操作模块
             * </pre>
             *
             * <code>uint32 module = 5;</code>
             *
             * @return The module.
             */
            @Override
            public int getModule() {
                return module_;
            }

            /**
             * <pre>
             * 操作模块
             * </pre>
             *
             * <code>uint32 module = 5;</code>
             *
             * @param value The module to set.
             * @return This builder for chaining.
             */
            public Builder setModule(int value) {

                module_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作模块
             * </pre>
             *
             * <code>uint32 module = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModule() {

                module_ = 0;
                onChanged();
                return this;
            }

            private long createUserId_;

            /**
             * <pre>
             * 创建人
             * </pre>
             *
             * <code>uint64 createUserId = 6;</code>
             *
             * @return The createUserId.
             */
            @Override
            public long getCreateUserId() {
                return createUserId_;
            }

            /**
             * <pre>
             * 创建人
             * </pre>
             *
             * <code>uint64 createUserId = 6;</code>
             *
             * @param value The createUserId to set.
             * @return This builder for chaining.
             */
            public Builder setCreateUserId(long value) {

                createUserId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 创建人
             * </pre>
             *
             * <code>uint64 createUserId = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCreateUserId() {

                createUserId_ = 0L;
                onChanged();
                return this;
            }

            private long companyId_;

            /**
             * <pre>
             * 公司ID
             * </pre>
             *
             * <code>uint64 companyId = 7;</code>
             *
             * @return The companyId.
             */
            @Override
            public long getCompanyId() {
                return companyId_;
            }

            /**
             * <pre>
             * 公司ID
             * </pre>
             *
             * <code>uint64 companyId = 7;</code>
             *
             * @param value The companyId to set.
             * @return This builder for chaining.
             */
            public Builder setCompanyId(long value) {

                companyId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 公司ID
             * </pre>
             *
             * <code>uint64 companyId = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCompanyId() {

                companyId_ = 0L;
                onChanged();
                return this;
            }

            private Object createTime_ = "";

            /**
             * <pre>
             * 创建时间
             * </pre>
             *
             * <code>string createTime = 8;</code>
             *
             * @return The createTime.
             */
            public String getCreateTime() {
                Object ref = createTime_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    createTime_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 创建时间
             * </pre>
             *
             * <code>string createTime = 8;</code>
             *
             * @return The bytes for createTime.
             */
            public com.google.protobuf.ByteString
            getCreateTimeBytes() {
                Object ref = createTime_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    createTime_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 创建时间
             * </pre>
             *
             * <code>string createTime = 8;</code>
             *
             * @param value The createTime to set.
             * @return This builder for chaining.
             */
            public Builder setCreateTime(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                createTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 创建时间
             * </pre>
             *
             * <code>string createTime = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCreateTime() {

                createTime_ = getDefaultInstance().getCreateTime();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 创建时间
             * </pre>
             *
             * <code>string createTime = 8;</code>
             *
             * @param value The bytes for createTime to set.
             * @return This builder for chaining.
             */
            public Builder setCreateTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                createTime_ = value;
                onChanged();
                return this;
            }

            private Object operationObj_ = "";

            /**
             * <pre>
             * 操作对象
             * </pre>
             *
             * <code>string operation_obj = 9;</code>
             *
             * @return The operationObj.
             */
            public String getOperationObj() {
                Object ref = operationObj_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    operationObj_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 操作对象
             * </pre>
             *
             * <code>string operation_obj = 9;</code>
             *
             * @return The bytes for operationObj.
             */
            public com.google.protobuf.ByteString
            getOperationObjBytes() {
                Object ref = operationObj_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    operationObj_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 操作对象
             * </pre>
             *
             * <code>string operation_obj = 9;</code>
             *
             * @param value The operationObj to set.
             * @return This builder for chaining.
             */
            public Builder setOperationObj(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                operationObj_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作对象
             * </pre>
             *
             * <code>string operation_obj = 9;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearOperationObj() {

                operationObj_ = getDefaultInstance().getOperationObj();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作对象
             * </pre>
             *
             * <code>string operation_obj = 9;</code>
             *
             * @param value The bytes for operationObj to set.
             * @return This builder for chaining.
             */
            public Builder setOperationObjBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                operationObj_ = value;
                onChanged();
                return this;
            }

            private Object operationInfo_ = "";

            /**
             * <pre>
             * 操作详情
             * </pre>
             *
             * <code>string operation_info = 10;</code>
             *
             * @return The operationInfo.
             */
            public String getOperationInfo() {
                Object ref = operationInfo_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    operationInfo_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 操作详情
             * </pre>
             *
             * <code>string operation_info = 10;</code>
             *
             * @return The bytes for operationInfo.
             */
            public com.google.protobuf.ByteString
            getOperationInfoBytes() {
                Object ref = operationInfo_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    operationInfo_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 操作详情
             * </pre>
             *
             * <code>string operation_info = 10;</code>
             *
             * @param value The operationInfo to set.
             * @return This builder for chaining.
             */
            public Builder setOperationInfo(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                operationInfo_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作详情
             * </pre>
             *
             * <code>string operation_info = 10;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearOperationInfo() {

                operationInfo_ = getDefaultInstance().getOperationInfo();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作详情
             * </pre>
             *
             * <code>string operation_info = 10;</code>
             *
             * @param value The bytes for operationInfo to set.
             * @return This builder for chaining.
             */
            public Builder setOperationInfoBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                operationInfo_ = value;
                onChanged();
                return this;
            }

            private Object equipmentType_ = "";

            /**
             * <pre>
             * 访问类型
             * </pre>
             *
             * <code>string equipmentType = 11;</code>
             *
             * @return The equipmentType.
             */
            public String getEquipmentType() {
                Object ref = equipmentType_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    equipmentType_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 访问类型
             * </pre>
             *
             * <code>string equipmentType = 11;</code>
             *
             * @return The bytes for equipmentType.
             */
            public com.google.protobuf.ByteString
            getEquipmentTypeBytes() {
                Object ref = equipmentType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    equipmentType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 访问类型
             * </pre>
             *
             * <code>string equipmentType = 11;</code>
             *
             * @param value The equipmentType to set.
             * @return This builder for chaining.
             */
            public Builder setEquipmentType(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                equipmentType_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 访问类型
             * </pre>
             *
             * <code>string equipmentType = 11;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEquipmentType() {

                equipmentType_ = getDefaultInstance().getEquipmentType();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 访问类型
             * </pre>
             *
             * <code>string equipmentType = 11;</code>
             *
             * @param value The bytes for equipmentType to set.
             * @return This builder for chaining.
             */
            public Builder setEquipmentTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                equipmentType_ = value;
                onChanged();
                return this;
            }

            private int type_;

            /**
             * <pre>
             * 操作类型
             * </pre>
             *
             * <code>uint32 type = 12;</code>
             *
             * @return The type.
             */
            @Override
            public int getType() {
                return type_;
            }

            /**
             * <pre>
             * 操作类型
             * </pre>
             *
             * <code>uint32 type = 12;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 操作类型
             * </pre>
             *
             * <code>uint32 type = 12;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Entity)
        }

        // @@protoc_insertion_point(class_scope:Entity)
        private static final Entity DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Entity();
        }

        public static Entity getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Entity>
                PARSER = new com.google.protobuf.AbstractParser<Entity>() {
            @Override
            public Entity parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Entity(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Entity> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Entity> getParserForType() {
            return PARSER;
        }

        @Override
        public Entity getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Entity_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Entity_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\020OperateLog.proto\"\360\001\n\006Entity\022\022\n\nrequest" +
                        "Uri\030\001 \001(\t\022\020\n\010behavior\030\002 \001(\r\022\r\n\005apply\030\003 \001" +
                        "(\r\022\020\n\010clientIp\030\004 \001(\t\022\016\n\006module\030\005 \001(\r\022\024\n\014" +
                        "createUserId\030\006 \001(\004\022\021\n\tcompanyId\030\007 \001(\004\022\022\n" +
                        "\ncreateTime\030\010 \001(\t\022\025\n\roperation_obj\030\t \001(\t" +
                        "\022\026\n\016operation_info\030\n \001(\t\022\025\n\requipmentTyp" +
                        "e\030\013 \001(\t\022\014\n\004type\030\014 \001(\rB\022B\020OperateLogEntit" +
                        "yb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Entity_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Entity_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Entity_descriptor,
                new String[]{"RequestUri", "Behavior", "Apply", "ClientIp", "Module", "CreateUserId", "CompanyId", "CreateTime", "OperationObj", "OperationInfo", "EquipmentType", "Type",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
